version: '3.8'
services:
  payload:
    image: node:20.10-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm run build && pnpm run start"
    env_file:
      - .env

volumes:
  node_modules:

